### ISSUE TITLE
Diamond Cow no output

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#12]
Diamond cow has no output for making blocks liek all other materials

![image](https://user-images.githubusercontent.com/29345907/193326645-5e7a32d7-f128-4043-b45d-a70ba77391f2.png)

![image](https://user-images.githubusercontent.com/29345907/193326619-bce75233-80da-43fd-93b7-72b7cb3690a6.png)

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/193379523-d65fdc5c-2fbf-4bb8-b622-91708860bfce.png)

added a output for a diamond block in the castin basin
