### ISSUE TITLE
Cant get T4 Blood altar cus loop

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#13]
T4 altar needs bloodstone bricks, which needs weak blood shard, which needs diamond sword, which needs diamond cow, which needs Tier 4 altar.

**Comment by fatpally** [comment]
The bound blade should get the shards but realizing that you cant get diamonds before that i added this recipe to the game
![image](https://user-images.githubusercontent.com/18649162/193379574-871ecfff-482b-440a-b861-c473b027c6fc.png)
creating the bound blade with a gold sword
