### ISSUE TITLE
Grains of infinity

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#16]
No way of getting grains of infinity cus no bedrock or anything

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/193379477-4de7e430-9533-4e2c-88d7-19c13a6f275d.png)

recipe will be tossing a glowstone dust into liquid coal

**Comment by itsjusttriz** [comment]
Still missing from latest update
