### ISSUE TITLE
Quartz Cow

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#17]
Not sure if i already posted an issue for this, but i remember us talking about it in Discord. But this cow still needs a recipe so we can have quartz for the Simple Storage setup.

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/193438502-4b506ab7-1f6e-45f5-98d5-659b5bc62e11.png)

**Comment by fatpally** [comment]
its a 5 percent chance
