### ISSUE TITLE
Grains of Infinity - REOPENED

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#19]
Referencing Issue #16

You mentioned it in the changelogs for Beta 12, but it was in fact missing from that update too.

**Comment by fatpally** [comment]
ok

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/193439162-64569154-823d-494a-8619-6bb557b6a88d.png)
 and
![image](https://user-images.githubusercontent.com/18649162/193439174-ccdc3f85-4589-4078-b358-2123c78a4e47.png)
