### ISSUE TITLE
Demon Will

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#21]
Using the Rudimentary Snares on sheep to try to get Demon will, but i feel like the item has been removed from the drops altogether cus ive used well over a stack of snares and havent gotten a single demonic will yet.... Maybe a new recipe for a basic demon will, e.g. weak blood orb in liquid life essence or something? Seems suitable

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/193437593-2959c067-bcad-4309-b838-b385e81050ef.png)
