### ISSUE TITLE
Grains of Infinity - REOPENED #2

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#22]
Referencing #19 

Liquifacted Coal cannot be placed so cant make grains of infinity.

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/193470845-68aac303-863e-4b77-aa1e-ca13358fc00c.png)

**Comment by fatpally** [comment]
it now requires dark oak fluid which can be placed
