### ISSUE TITLE
No method of retrieving AE presses

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#29]
![image](https://user-images.githubusercontent.com/29345907/194781091-1989ba4c-7676-4151-971a-7b54b1270459.png)
Need presses for these.

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/194874220-b5123e66-b059-45a4-a1e6-81d2f7326be9.png)


![image](https://user-images.githubusercontent.com/18649162/194870632-5e0b05f4-6f2c-4adf-93f4-0e85cee5380d.png)

![image](https://user-images.githubusercontent.com/18649162/194870704-66112ab3-ac2e-49b9-b390-d635e01f26ce.png)

![image](https://user-images.githubusercontent.com/18649162/194871342-bb505927-2d5e-42c1-9d24-d52b1672a0a1.png)
