### ISSUE TITLE
Sky Stone

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#30]
Need a way of getting smooth (**_not raw_**) sky stone for making the ME controller, plskthx :)

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/195084970-a19a7261-c506-43c6-a028-67bef7284633.png)
 Its oredict so any pulverized coal will work you will then need to interact with a stone barrel

**Comment by fatpally** [comment]
adding in a furnace recipe as well thats not indicated in this issue thread
