### ISSUE TITLE
Conflicting Recipe - Nether Star

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#31]
![image](https://user-images.githubusercontent.com/29345907/195988283-2d2cd87f-3b85-4ee7-8b42-41f420e8363a.png)
These would conflict

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/196088639-e5015d40-b514-48f9-972f-bb7b99e4de76.png)
recipe is fixed for the cow at least
