### ISSUE TITLE
Missing craft to get Resonant Ender cow

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#4]
Resonant Ender cow needs to be craftable to make EIO conduits later on

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/192397126-59992207-c39c-4b98-9cfe-63d73ecfec94.png)

**Comment by fatpally** [comment]
made a recipe for those that want and those that dont want to kill mobs.

**Comment by itsjusttriz** [comment]
> made a recipe for those that want and those that dont want to kill mobs.

<3
