### ISSUE TITLE
Conflicting Weak Blood orb recipe

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#5]
I think the Emerald cow recipe is conflicting with the weak blood orb recipe, causing neither to be craftable:

![image](https://user-images.githubusercontent.com/29345907/192568927-0523f974-dccc-4bf2-88d6-40cdf7a2277c.png)

**Comment by fatpally** [comment]
It has been fixed will push out with a new update 
![image](https://user-images.githubusercontent.com/18649162/192596532-3ae10dd3-b03c-4323-b4f6-419ea36da44f.png)
