### ISSUE TITLE
Glass unobtainable

### ISSUE THREAD

**Issue by itsjusttriz** [fatpally/cowcraft#7]
(Sand -> Glass) recipe missing from furnace
Glass cow has no craft recipe.

Cannot get glass

**Comment by fatpally** [comment]
![image](https://user-images.githubusercontent.com/18649162/192615618-d28b2b1f-4327-4074-be3b-2ec8ca22d940.png)
recipe for glass cow breedable with sand and lava cows
and i removed the clear glass
![image](https://user-images.githubusercontent.com/18649162/192615703-435768c9-cc6d-43f3-8b11-f27313a129a6.png)
so it only outputs glass
